import { tool } from "@opencode-ai/plugin";
import { readdir, stat } from "node:fs/promises";
import path from "node:path";
import type { SessionState } from "../../core/state/session.js";
import type { ToolRegistry } from "../types.js";
import { formatError } from "../build/index.js";
import { zipDirectory } from "./zip.js";

/**
 * Directories excluded by default. These are dependency caches and build output
 * that should never be uploaded: they are large, regenerated by install_commands
 * and build_commands on the runner, and frequently contain absolute paths from
 * another machine that would break the build.
 */
export const DEFAULT_EXCLUDE_DIRS = [
  "node_modules",
  "dist",
  "build",
  "out",
  ".next",
  ".nuxt",
  ".svelte-kit",
  ".output",
  ".turbo",
  ".cache",
  ".parcel-cache",
  "coverage",
  ".venv",
  "venv",
  "__pycache__",
  ".pytest_cache",
  ".mypy_cache",
  ".tox",
  "target",
  ".gradle",
  "vendor",
  ".terraform",
  ".git",
  ".idea",
  ".vscode",
];

const EXCLUDE_FILES = new Set([
  ".DS_Store",
  "Thumbs.db",
  "npm-debug.log",
  "yarn-error.log",
  "pnpm-debug.log",
]);

const MAX_FILE_BYTES = 20 * 1024 * 1024;
const MAX_TOTAL_BYTES = 400 * 1024 * 1024;

interface Collected {
  files: string[];
  totalBytes: number;
  skipped: string[];
}

async function collect(
  root: string,
  excludeDirs: Set<string>,
  current: string
): Promise<Collected> {
  const result: Collected = { files: [], totalBytes: 0, skipped: [] };

  let entries;
  try {
    entries = await readdir(current, { withFileTypes: true });
  } catch {
    return result;
  }

  for (const entry of entries) {
    const full = path.join(current, entry.name);

    if (entry.isDirectory()) {
      if (excludeDirs.has(entry.name)) continue;
      const nested = await collect(root, excludeDirs, full);
      result.files.push(...nested.files);
      result.totalBytes += nested.totalBytes;
      result.skipped.push(...nested.skipped);
      continue;
    }

    if (!entry.isFile()) continue;
    if (EXCLUDE_FILES.has(entry.name)) continue;

    let info;
    try {
      info = await stat(full);
    } catch {
      continue;
    }

    if (info.size > MAX_FILE_BYTES) {
      result.skipped.push(`${path.relative(root, full)} (too large)`);
      continue;
    }

    result.files.push(full);
    result.totalBytes += info.size;
  }

  return result;
}

export function createProjectTools(state: SessionState): ToolRegistry {
  const uploadProject = tool({
    description: [
      "Package the project source and upload it to the platform so it can be built.",
      "",
      "This is the first step of any build. It archives the project directory,",
      "skipping dependency caches and build output, then uploads the archive.",
      "After uploading, call build_submit to run the install and build commands in",
      "GitHub Actions against this uploaded code.",
      "",
      "Use exclude_dirs to control what is skipped. The defaults already cover the",
      "common cases. Passing exclude_dirs REPLACES the default list, so re-include",
      "any default names you still want excluded, and add project-specific ones",
      "such as generated SDK output or vendored bundles.",
    ].join("\n"),
    args: {
      project_id: tool.schema
        .string()
        .describe("The project id to create or update with this upload"),
      path: tool.schema
        .string()
        .optional()
        .describe("Project directory to upload. Defaults to the OpenCode worktree root."),
      exclude_dirs: tool.schema
        .array(tool.schema.string())
        .optional()
        .describe(
          "Directory names to exclude from the archive. Replaces the default list: " +
            "node_modules, dist, build, out, .next, .nuxt, .svelte-kit, .output, .turbo, " +
            ".cache, .parcel-cache, coverage, .venv, venv, __pycache__, .pytest_cache, " +
            ".mypy_cache, .tox, target, .gradle, vendor, .terraform, .git, .idea, .vscode. " +
            "Always exclude dependency directories and build output: they are reinstalled " +
            "by install_commands and regenerated by build_commands on the runner, so " +
            "uploading them wastes the upload and rarely helps."
        ),
      project_name: tool.schema.string().optional().describe("Display name for the project"),
    },
    async execute(args, context) {
      try {
        const root = path.resolve(args.path || (context as any).worktree || process.cwd());
        const excludeDirs = new Set(args.exclude_dirs ?? DEFAULT_EXCLUDE_DIRS);

        const collected = await collect(root, excludeDirs, root);

        if (collected.files.length === 0) {
          return `No files found under ${root}. Check the path and exclude_dirs.`;
        }

        if (collected.totalBytes > MAX_TOTAL_BYTES) {
          return [
            `Project is ${(collected.totalBytes / 1024 / 1024).toFixed(1)}MB, over the`,
            `${(MAX_TOTAL_BYTES / 1024 / 1024).toFixed(0)}MB upload limit.`,
            "Add directories to exclude_dirs, or upload a build artifact instead of full source.",
          ].join(" ");
        }

        const manifest = {
          files: collected.files
            .map((f) => path.relative(root, f).split(path.sep).join("/"))
            .sort(),
          total_bytes: collected.totalBytes,
          excluded: Array.from(excludeDirs).sort(),
        };

        const form = new FormData();
        form.append("project_id", args.project_id);
        if (args.project_name) form.append("project_name", args.project_name);
        form.append("manifest", JSON.stringify(manifest));
        form.append(
          "file",
          new Blob([await zipDirectory(root, collected.files)], { type: "application/zip" }),
          `${args.project_id}.zip`
        );

        const result = await state.api.upload<{
          project_id: string;
          upload_id: string;
          sha256: string;
          file_count: number;
          total_bytes: number;
        }>("/api/v1/projects/upload", form);

        const lines = [
          `Uploaded ${result.file_count} files (${(result.total_bytes / 1024).toFixed(0)}KB) for project ${result.project_id}.`,
          `upload_id: ${result.upload_id}`,
          `sha256: ${result.sha256}`,
        ];

        if (collected.skipped.length > 0) {
          lines.push(
            `skipped ${collected.skipped.length} oversized file(s): ${collected.skipped
              .slice(0, 5)
              .join(", ")}`
          );
        }

        lines.push("Now call build_submit with install_commands and build_commands.");
        return lines.join("\n");
      } catch (err) {
        return formatError(err);
      }
    },
  });

  return { project_upload: uploadProject };
}
